const StateData = {
  disciplineAni: [],
  capitole: [],
  topics: [],
  tests1: [],
  tests2: [],
  tests3: [],
  tests4: [],
  tests5: [],
  tests6: [],
  tests7: [],
  tests8: [],
  tests9: [],
  tests10: [],
  tests11: [],
  evaluations: [],
  evaluations1: [],
  evaluations2: [],
  evaluations3: [],
  breadcrumb: [],
  currentLevel: 1,
  currentSubject: null,
  currentTheme: null,
  currentTopic: null,
  currentTests: [],
  currentStudent: 1,
  currentYear: 2022,
  themeVideo: null,
}
export default StateData